void process_input(char a, struct Plants plants[], int *plantAmount, struct PlantSensors *curPlant);
void delay(int mSeconds);
void invalid_input();
void read_data(struct PlantSensors *current);
void overwrite_data(struct PlantSensors *current);
void edit_data(struct PlantSensors *current, int sprinklerState);
void setup(struct PlantSensors *current);
void print_plant(struct Plants current);
void list_plants(struct Plants plants[], int plantAmount);
void init_structs(struct Plants plants[]);
void edit_mode(struct Plants plants[], int *plantAmount);   
void edit_plant(struct Plants *current);
void debug_mode(struct PlantSensors *current);
int cmp_nums(float a, float b);
